import { parse, stringify } from 'smol-toml'
import { ConfigSchema, type SwarmConfig, defaultConfig } from './schema'
import { homedir } from 'os'
import { join } from 'path'
import { mkdir } from 'fs/promises'

export const CONFIG_DIR = join(homedir(), '.swarm')
export const CONFIG_PATH = join(CONFIG_DIR, 'config.toml')

export async function loadConfig(): Promise<SwarmConfig> {
  const file = Bun.file(CONFIG_PATH)
  const exists = await file.exists()
  if (!exists) {
    return defaultConfig
  }

  try {
    const text = await file.text()
    const parsed = parse(text)
    return ConfigSchema.parse(parsed)
  } catch (err) {
    console.warn('[swarm/config] Failed to parse config, using defaults:', err)
    return defaultConfig
  }
}

export async function saveConfig(config: SwarmConfig): Promise<void> {
  await mkdir(CONFIG_DIR, { recursive: true })
  const body = stringify(config as Parameters<typeof stringify>[0])
  const header = '# Swarm config — https://github.com/jeffblakely/swarm\n# Generated by swarm\n\n'
  await Bun.write(CONFIG_PATH, header + body)
}

export async function initConfig(): Promise<void> {
  const file = Bun.file(CONFIG_PATH)
  const exists = await file.exists()
  if (!exists) {
    await saveConfig(defaultConfig)
  }
}

export function resolveProviderKey(config: SwarmConfig, provider: string): string | undefined {
  switch (provider) {
    case 'anthropic':
      return config.providers.anthropic.api_key ?? process.env.ANTHROPIC_API_KEY
    case 'openrouter':
      return config.providers.openrouter.api_key ?? process.env.OPENROUTER_API_KEY
    case 'replicate':
      return config.providers.replicate.api_key ?? process.env.REPLICATE_API_KEY
    case 'ollama':
      return undefined
    default:
      return undefined
  }
}

export function resolveBaseUrl(config: SwarmConfig, provider: string): string | undefined {
  switch (provider) {
    case 'ollama':
      return config.providers.ollama.base_url
    case 'openrouter':
      return config.providers.openrouter.base_url
    default:
      return undefined
  }
}
